version: "3"

services:
  strapi_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/app/
    ports:
      - "1337:1337"
    command: sh -c "npm run build && npm start"
